[ODOO-3941][UPD][foreign_purchase_order]Modifications made requested by the client
calyx-servicios/halpern-masteragua pull request #18
Opened 2022-08-09 19:48 UTC by lucianobaleani

2022-08-11 12:04 UTC, FedericoGregori requested changes

2022-08-11 12:04 UTC, FedericoGregori commented on foreign_purchase_order/i18n/es_AR.po
> +msgstr ""
Falta traducción

2022-08-11 12:04 UTC, FedericoGregori commented on foreign_purchase_order/i18n/es_AR.po
> +msgid "Document Coverage Number"
Falta traducción

2022-08-11 12:04 UTC, FedericoGregori commented on foreign_purchase_order/models/purchase_order.py
> +    document_packing_list = fields.Boolean()
Analizar si esto podría ser un campo relacional/selection. No deberían existir tantos campos booleanos si existen situaciones de disyunción

2022-08-11 12:04 UTC, FedericoGregori commented on foreign_purchase_order/models/purchase_order.py
> +    payment_supplier_currency = fields.Selection(selection=[("eur", "EUR"),
Analizar si es posible crear otra tabla para payment, o utilizar account payment creando un nuevo tipo, en lugar de crear tantos campos porque perjudica la escalabilidad

2022-08-16 16:47 UTC, lucianobaleani commented on foreign_purchase_order/models/purchase_order.py
> +    document_packing_list = fields.Boolean()
Puede ser un selection(Yes/No). Adjunto lo solicitado por el cliente:

- Crear sub ítem, nombre del mismo: PACKING LIST. **_Para completar con si o no_**. 

Varios de los campos boolean tiene la misma petición

2022-08-18 21:33 UTC, FedericoGregori approved these changes

2022-08-18 21:33 UTC, merged